### ISSUE TITLE
Rookie PCVR 1.5 error

### ISSUE THREAD

**Issue by Yoda49** [VRPirates/rookie-pcvr#20]
Unable to connect to remote server

**Comment by Fenopy** [comment]
**VRP Update – May 13, 2024 | Deprecation of Rookie-PCVR**

Dear VRP Community,

Due to high server costs and low traffic, we regret to inform you that as of May 20, 2024, we will be shutting down the Free PCVR Mirror. We will continue to provide PCVR updates on our Private Mirror for those interested.

THIS DOES NOT IMPACT THE ROOKIE-QUEST-GAMES FREE MIRROR.

As an alternative, we highly recommend ARMGDDN (https://t.me/ARMGDDNGames).

Thank you for your understanding.
~ VRP Team
